"use client";
import { Metadata } from "next";
import { IconContext } from "@phosphor-icons/react";
import { Navbar } from "@/app/components";
import {
  Overview,
  Photos,
  Video,
  FloorPlan,
  VirtualTour,
  Contact,
} from "./components";
import { SectionPropTypes } from "@/app/types";

export const metadata: Metadata = {
  title: "Jakhaus Listings",
  description: "Generated by create next app",
};

export const Listing = ({ CONSTANTS, FULL_ADDRESS }: SectionPropTypes) => {
  return (
    <IconContext.Provider value={{ size: 24, weight: "light" }}>
      <Navbar CONSTANTS={CONSTANTS} />
      <Overview CONSTANTS={CONSTANTS} FULL_ADDRESS={FULL_ADDRESS} />
      <div className="grid grid-cols-4 gap-5 md:grid-cols-8 lg:grid-cols-12">
        <div className="col-span-full grid grid-cols-4 gap-5 border-x border-x-neutral-300 pt-5 pb-10 md:grid-cols-8 lg:col-span-10 lg:col-start-2 lg:grid-cols-10">
          <Photos CONSTANTS={CONSTANTS} FULL_ADDRESS={FULL_ADDRESS} />
          {CONSTANTS.VIDEO_LINK && (
            <Video CONSTANTS={CONSTANTS} FULL_ADDRESS={FULL_ADDRESS} />
          )}
          {CONSTANTS.FLOOR_PLAN && (
            <FloorPlan CONSTANTS={CONSTANTS} FULL_ADDRESS={FULL_ADDRESS} />
          )}
          {CONSTANTS.SCAN_LINK && (
            <VirtualTour CONSTANTS={CONSTANTS} FULL_ADDRESS={FULL_ADDRESS} />
          )}
        </div>
      </div>
      <Contact CONSTANTS={CONSTANTS} />
    </IconContext.Provider>
  );
};
